### ISSUE TITLE
Odstrani website-aokranj.com-tmp-by-bojc* repote

### ISSUE THREAD

**Issue by bostjan** [aokranj/infrastructure#36]
Pa se gatsby repo naj se preveri/odstrani.

**Comment by bostjan** [comment]
Done:
- `aokranj/website-aokranj.com-tmp-by-bojc2` (a clone of our main repo, with only `wp-graphql` and `wp-gatsby` plugins added (in a disabled state))

**Comment by HriBB** [comment]
@bostjan daj samo počakaj še malo, da jest pregledam, kje in kako imam aokranj gatsby verzijo. Bom en dan malo zrihtal, in dodal `aokranj-gatsby` in `pdkranj-gatsby` repozitorija, če se strinjaš.

**Comment by bostjan** [comment]
Np, ti kar v miru poglej.

Itak, novi repoti niso problem, ce se rabijo.

Ampak: ce samo menjamo kodo, ki poganja naso spletno stran, potem najbrz ne rabimo _novega_ repota, ampak je najbrz enostavneje, da pac staro kodo zamenjamo z novo kodo v obstojecem repotu z enim commitom in smo done, right?

PS: Ce se rabi zacasni eksperimentalni repo, seveda. Edino cesar bi se zelel izognit je, da zapusceni testni/experimentalni repoti leta lezijo po AO github accountu, in da se vsak, ki pride po mesecih pavze kej spet posravfat, sprasuje, cemu tocno ze sluzijo. Tako stanje tudi ne mece najboljse luci na javni AO github org - za hostanje napol zapuscenih idej imamo itak vsi vsak svoj github account ;)

**Comment by bostjan** [comment]
@HriBB, ping? Si ze uspel pogledat/pregledat tole? Tnx.

**Comment by HriBB** [comment]
@bostjan nisem, trenutno mam kr akcije v službi, ko se stvari malo umirijo, se lotim telih stvari.

Kaj pa, če preprosto preneseš repo name, pa bom jest preveril ali rabim še kaj iz tam?

**Comment by bostjan** [comment]
@HriBB, to bi bil pa kar security issue, ce bi lahko jaz sam izvedel prenos repota v _tvoj_ account brez tvoje pomoci :)

Sem pa imel isto v mislih. A lahko kar uporabis opcijo `Transfer Ownership` na dnu nastavitev na tehle dveh linkih?
* https://github.com/aokranj/website-aokranj.com-tmp-by-bojc/settings
* https://github.com/aokranj/gatsby/settings

Tnx.

![image](https://user-images.githubusercontent.com/107080/194063641-3675fb68-7722-4ca2-bd7e-fb271d693965.png)

**Comment by bostjan** [comment]
Pa se dva repota sem nasel, in sicer v `pdkranj` github org-u:
* https://github.com/pdkranj/gatsby
* https://github.com/pdkranj/website

A tole pade v isti koš, se tudi odstrani?

**Comment by bostjan** [comment]
Vseskupaj premaknjeno v [@Hribb-tmp](https://github.com/HriBB-tmp).

@HriBB, si owner @HriBB-tmp, preglej zadeve, ko boš pri času. Pa ko boš pregledoval, me prosim še odstrani s HriBB-tmp organizacije, tnx.
