### ISSUE TITLE
Ponovno vzpostavi Bojcev account

### ISSUE THREAD

**Issue by bostjan** [aokranj/infrastructure#39]
(ker se ni bil prestavljen s starega serverja)

@HriBB, a mi pls posljes tvoje javne SSH kljuce?

**Comment by HriBB** [comment]
@bostjan a ti jih posljem kar na mail?

**Comment by bostjan** [comment]
@HriBB, lahko mail, lahko na Whatsapp, al pa Signal.

**Comment by bostjan** [comment]
@HriBB, kasn mas preferred username? "bojan", "bojc", kej druzga?

**Comment by bostjan** [comment]
@HriBB se PW si pls spremeni na sistemu pa sva done.

**Comment by bostjan** [comment]
Dev vhosta na Bojcovo zeljo tudi ustvarjena (#43).

**Comment by HriBB** [comment]
@bostjan sm updejtal password ;)
