### ISSUE TITLE
Poraba pomnilnika - potencialni upgrade

### ISSUE THREAD

**Issue by bostjan** [aokranj/infrastructure#44]
Po cca 5 mesecih uptime-a je imel streznik na voljo le se 250-400 MB RAM-a, kar je precej minimum za karkoli.
Po rebootu (prevsem zaradi upgrade-ov) je trenutno prostega rama za cca 1.6GB.

Pustim tole odprto za kak mesec ali dva, da potencialno nadgradimo iz 4GB na 8GB.

Screengrab iz netdata za zadnji dve uri (dva oranzna odtenka sta precej podobna, zal):
![image](https://user-images.githubusercontent.com/107080/184270110-67f88b31-0dc3-430f-b927-e53433104678.png)

**Comment by bostjan** [comment]
Se tale graf (procesi) kaze relevantno razliko pred in po rebootu:
![image](https://user-images.githubusercontent.com/107080/184270806-6e5375c8-7b85-4db4-9b8d-fa89f839032c.png)

**Comment by HriBB** [comment]
Če prav razumem, pač ni druge kot da nadgradimo ram? Se da kej optimizirat?

**Comment by bostjan** [comment]
Ce bi bilo kaj preprostega za optimizirat, bi ze:
- Kubernetes pozre cca 0.4-07GB (zal)
- MySQL gre tja do 1.1GB (pri tem da so inno bufferji omejeni na 0.5GB, kar je potencialno premalo, ker je nas dataset cca 1.3GB, mysqltuner prav da lahko max ram zraste tud do 2.8GB)
- Apache+PHP je variabilien, izgleda kot da je porabljal okrog 0.4GB pred rebootom, ampak od tega so 192MB (prod) in 128MB (devstg) samo za opcache, tako da je pomojem malce vec
- 0.4GB zgleda da ga tale netdata sys tracking tool porabi (tole ni malo!)
= cca 2.5GB
To je se brez ostalih procesov, ki laufajo na sistemu, in brez rama, ki ga porabi kernel, pa fino je, da je cca 20-50% rama frej za disk cache, ker drugac vse stvari hitro postanejo precej pocasnejse.

![image](https://user-images.githubusercontent.com/107080/184356766-085fbff5-ca2c-414c-8008-83719e8e6a7e.png)


Tole so porabniki po kontejnerjih:
```
13:34 $ docker stats --no-stream | grep MiB | grep -E '(kube|controller_ingress)'
3ae6069257b7   k8s_coredns_coredns-558bd4d5db-qvbnz_kube-system_4913e1be-1b89-4c41-a209-960f72bd7158_9                                            0.43%     12.89MiB / 170MiB     7.59%     0B / 0B   4.25MB / 0B       9
01270d4eea60   k8s_controller_ingress-nginx-controller-54bfb9bb-9qvhp_ingress-nginx_bfcf38fd-b63d-4464-a791-b28fbefd10a8_3                        0.11%     82.95MiB / 3.746GiB   2.16%     0B / 0B   90MB / 176kB      85
1c32ef4f2815   k8s_coredns_coredns-558bd4d5db-2kwts_kube-system_c5ad10ac-3bff-4fb9-a854-ad4841efb254_10                                           0.48%     15.48MiB / 170MiB     9.11%     0B / 0B   38.1MB / 0B       9
741a4bf6382b   k8s_kube-flannel_kube-flannel-ds-phth4_kube-system_a98052be-8b7d-4e58-9bee-00eb86ec81da_11                                         0.00%     15.4MiB / 50MiB       30.80%    0B / 0B   51.1MB / 0B       9
8ff39cfe8106   k8s_kube-proxy_kube-proxy-ml2nk_kube-system_3a7a8874-2667-435d-905b-ca53842d412f_10                                                0.48%     26.22MiB / 3.746GiB   0.68%     0B / 0B   69MB / 12.3kB     7
c92277232ec6   k8s_kube-controller-manager_kube-controller-manager-host1_kube-system_4e650431553104400ba4b714d2532643_33                          3.42%     61.85MiB / 3.746GiB   1.61%     0B / 0B   128MB / 0B        7
ad51bbc550b4   k8s_etcd_etcd-host1_kube-system_0a60dd8b9d14c120ca91f253da6aa89d_7                                                                 1.48%     51.34MiB / 3.746GiB   1.34%     0B / 0B   317MB / 1.25GB    12
9dc7bd776fca   k8s_kube-scheduler_kube-scheduler-host1_kube-system_3ee9d3aaa80483a132f309d226d6189d_32                                            0.21%     24.72MiB / 3.746GiB   0.64%     0B / 0B   66.1MB / 0B       9
8a6ebfb8a2ed   k8s_kube-apiserver_kube-apiserver-host1_kube-system_8b1c487b385c2f02c2c273481922f683_8                                             6.57%     323.1MiB / 3.746GiB   8.42%     0B / 0B   151MB / 0B        10

13:35 $ docker stats --no-stream | grep MiB | grep cert
42454525caa9   k8s_cert-manager_cert-manager-cainjector-967788869-n5gsz_cert-manager_95ff9169-8221-4adb-90ff-f79f4b9c411f_20                      0.18%     30.44MiB / 3.746GiB   0.79%     0B / 0B   43.3MB / 0B       9
3fc119356717   k8s_cert-manager_cert-manager-webhook-6668fbb57d-n27wf_cert-manager_80c47632-3ade-4253-ab48-5a54b214931d_16                        0.00%     18.66MiB / 3.746GiB   0.49%     0B / 0B   47.7MB / 0B       10
0b5bf77a1117   k8s_cert-manager_cert-manager-55658cdf68-fr52z_cert-manager_0c850168-824b-414a-a044-329c8e472266_21                                0.14%     25.49MiB / 3.746GiB   0.66%     0B / 0B   69.5MB / 0B       8

13:36 $ docker stats --no-stream | grep MiB | grep -E -v '(kube|controller_ingress)' | grep -v cert
a25c15080dce   k8s_tools-dev-aokranj-com-oauth2_tools-dev-aokranj-com-oauth2-dp-86c987df6b-84ksx_default_7d707d12-ded7-4ec4-9b9b-60163f2bb5f7_8   0.11%     7.344MiB / 3.746GiB   0.19%     0B / 0B   24.4MB / 0B       9
fd009ba09d09   k8s_mariadb_mariadb-dp-7948788764-c4h8x_default_014ae19d-ebb6-4a59-994e-6a3e09c0949c_31                                            0.02%     579.8MiB / 3.746GiB   15.12%    0B / 0B   684MB / 37.9MB    20
c90220fc8690   k8s_mail-out_mail-out-dp-857fd655c9-k4k5s_default_efd7aa37-a0a6-4640-9e8b-1647fd74d937_11                                          0.00%     8.242MiB / 3.746GiB   0.21%     0B / 0B   27.9MB / 65.5kB   1
9a345f620579   k8s_app-runtime-httpd-php-devstg_app-runtime-httpd-php-devstg-dp-7d78889d48-67nmz_default_b37ca0f6-d9ff-43a4-b75b-5c750ab5dfb0_3   0.01%     199.1MiB / 3.746GiB   5.19%     0B / 0B   270MB / 32.8kB    5
5015a9e081e7   k8s_ingress-error-page_ingress-error-page-dp-845579698c-cntdp_default_362561a4-b5d8-4f24-b7c8-251275efc196_9                       0.01%     5.875MiB / 3.746GiB   0.15%     0B / 0B   2.79MB / 0B       55
d2287726cab4   k8s_app-runtime-httpd-php-prod_app-runtime-httpd-php-prod-dp-544547857d-qrt99_default_9ef82e72-02b2-4fbc-882b-56a704b0128f_3       0.06%     313.4MiB / 3.746GiB   8.17%     0B / 0B   1.28GB / 0B       11

13:36 $ 
```

Uglavnem, razen ugasanja netdata daemona ne vidim ravno veliko prostora za optimizacijo, ne da pri tem kompromitiramo hitrost izvajanja nasih app-ov ali pa fleksibilnost okolja, ki jo trenutno imamo (k8s, locen dev itd)

**Comment by HriBB** [comment]
Ah potem sploh ni debate, nadgradi na 8GB, saj ne bo tolk drazje.

**Comment by bostjan** [comment]
Done, nadgrajeno na 8GB, na `CX31` instanco (2CPU, 8GB ram, 80GB disk*).

@katarinaAO, @mzupin, za par EUR/mesec bo sel racun gor (za ~4, ce se prav spomnim).

*Ta instanca pride z 80GB root diska, ampak pri nadgradnji imas opcijo `CPU and RAM only`, ki se ne dotika diska in je stvar takoj po rebootu nazaj v pogonu. Zaenkrat se nisem hotel ukvarjat z razsiritvijo diska, ker smo trenutno na cca 50% porabe originalnega 40GB root diska (glavni porabnik so docker kontejnerji in image-i). Ko bo potreba po vec, bomo pa razsirili root particijo na 80GB.

Trenutno stanje:
```shell
bostjan@host1:~$ free -h
              total        used        free      shared  buff/cache   available
Mem:          7.6Gi       1.7Gi       3.8Gi       123Mi       2.0Gi       5.5Gi
Swap:            0B          0B          0B
bostjan@host1:~$ 
```
(Predvsem ["buff/cache"](https://medium.com/marionete/linux-disk-cache-was-always-there-741bef097e7f) super izgleda zdejle, ker prej za tole res ni bilo prav veliko prostora.)

**Comment by bostjan** [comment]
Se screenshot grafa, za primerjavo z zacetnim stanjem s prvega komentarja v temle ticketu:
![image](https://user-images.githubusercontent.com/107080/188248441-9224fa26-a635-474c-a744-9daf70e7088a.png)
