### ISSUE TITLE
Organiziraj (predvidoma Zoom) srečanje 2022-10

### ISSUE THREAD

**Issue by bostjan** [aokranj/infrastructure#56]
Namen:
* Da se spoznamo
* Da odgovorimo na začetna vprašanja

Teme za prediskutirat:
* Hiter pregled razvoja app-ov in infrastrukture skozi cas
* Ideje za razvoj
* Je kdo na Windowsih (in moramo zato prilagoditi development okolje)? 
* @HriBB v torek, 4.10. ne more, lahko pa cetrtek/petek isti teden popoldne - lahko se dogovorimo za se en klic na enega izmed teh dveh dni, obelava tematike bolj z dev perspektive (torek bolj z ops zornega kota).

Opcijsko:
* wp-cli-configmaps
* GatsbyJS

**Comment by bostjan** [comment]
@andrazjelenc, @jernej-m, @jernejstern, kdaj se lahko dobimo na enem 20 minutnem Zoom-u, recimo naslednji teden?

Recimo ponedeljek, 3.10. ob 18h, bi šlo?
Če ne, a se lahko med seboj uskladite za dva termina, ki vam vsem trem ustrezata, pa ju pripopate semle, pa bom za enega zagotovo našel čas. 

(@JNastran, @HriBB, FYI & vljudno vabljena.)

**Comment by jernejstern** [comment]
oj, men je torek ok!
